name: deflaking-on-github

on:
  push:
    branches:
      - deflake-ui-tests  # debug this workflow
  schedule:
    # Every 45 min on weekday nights (between 8 pm and 7 am PST)
    - cron:  '*/45 3-14 * * 1-5' # https://crontab.guru/#*/45_3-14_*_*_1-5
    # Every 45 min on weekend
    - cron:  '*/45 * * * 0,6'  # https://crontab.guru/#*/45_*_*_*_0,6

jobs:
  test-continously:
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
      NSUnbufferedIO: YES
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Prepare macOS runner
      uses: paulz/prepare-macos@v1
    - uses: actions/checkout@v2.3.1
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/cache@v2.1.1
      with:
        path: vendor/bundle
        key: bundled-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: ruby bundle
      run: |
        ruby --version
        bundler --version
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: deflake UI Tests
      env:
        SUBMIT_METRICS_URL: ${{ secrets.SUBMIT_METRICS_URL }}
        TIME_LIMIT_MINUTES: 25 
      run: |
        bin/dev/deflake-ui-tests.sh
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: |
        cp $TMPDIR/events-detected-during-ui-tests.txt . || true
        zip -r results.zip test-results/ui-tests-latest.xcresult || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
    - name: Upload events
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: events-detected-during-ui-tests.txt
        path: events-detected-during-ui-tests.txt
        if-no-files-found: ignore
